### ISSUE TITLE
White screen and crash on alt tab

### ISSUE THREAD

**Issue by sevcikfi** [pj1234678/MagickaFix#2]
when altabing the game, screen turns white and it hard crashes

**Comment by pj1234678** [comment]
Hey Thanks for the report.
Could you upload your crashlog pertaining to this?
It should be inside the game folder.

Also could you list your CPU/GPU make and model?

**Comment by pj1234678** [comment]
It has been a few months since this issue.

In the latest update I addressed a lot of memory concerns.

Please update to the latest fixes and open a new issue if need be.
