### ISSUE TITLE
[Proton] Low RAM warning box always triggers

### ISSUE THREAD

**Issue by Torston420** [pj1234678/MagickaFix#6]
Proton 8.0-3, Artix Linux
The low RAM warning message box will always trigger regardless of the amount of available RAM I have
Output of 'free -h' after booting the game to show that I have more than enough:
```
               total        used        free      shared  buff/cache   available
Mem:            15Gi       8.3Gi       2.9Gi       585Mi       8.1Gi       7.3Gi
Swap:          4.0Gi          0B       4.0Gi
```

This does not impede gameplay, but it does slow down the game's boot time. Perhaps implement a command line option to skip the warning?

**Comment by pj1234678** [comment]
This has been fixed in V1.3 Please test and advice.
