### ISSUE TITLE
Magicka Won't Launch After Applying Fix.

### ISSUE THREAD

**Issue by Silencer59** [pj1234678/MagickaFix#7]
As the title suggest, the game will refuse to start after applying this fix.

Specs:
OS: Windows 10 Pro
CPU: Intel Core i7-6900K
RAM: 32GB DDR4
Graphics: Nvidia RTX 3090Ti

Attached is the error log generated by the game when attempting to start from Steam.
[errorReport_2023.10.25-08.08.03.txt](https://github.com/pj1234678/MagickaFix/files/13171694/errorReport_2023.10.25-08.08.03.txt)

**Comment by pj1234678** [comment]
This has been fixed in V1.3 Please test and advice

**Comment by Silencer59** [comment]
Tested and working. Thank you for the quick fix. 👍
