### ISSUE TITLE
Chapter end crash

### ISSUE THREAD

**Issue by Murchante** [pj1234678/MagickaFix#8]
hi i had a crash after finishing chapter 1 with the fixes installed here's my crash log
https://pastebin.com/GNNkSH9W

I have an nvidia 3060 ti, ryzen 7 5800x, 16 gb 3200 mhz corsair vengence ram

**Comment by pj1234678** [comment]
Thank you for the report.
I finally found a solution, Since the binary runs in 32 bit mode it can't use more than ~1.3GB of ram.
In version 1.5 I address this by adding the LARGEADDRESSAWARE flag to the binary header.

I will mark this closed when 1.5 drops in a few hours.

**Comment by pj1234678** [comment]
The new version dropped, Addressing a lot of these concerns
Please update and if you have the same issue open a new one.
