### ISSUE TITLE
tryed the patch and still crashes to desktop

### ISSUE THREAD

**Issue by MishkaRose** [pj1234678/MagickaFix#9]
[errorReport_2023.12.21-04.12.27_(1).txt](https://github.com/pj1234678/MagickaFix/files/13746571/errorReport_2023.12.21-04.12.27_.1.txt)
[errorReport_2023.12.21-03.48.41_(1).txt](https://github.com/pj1234678/MagickaFix/files/13746572/errorReport_2023.12.21-03.48.41_.1.txt)

**Comment by MishkaRose** [comment]
[errorReport_2023.12.21-05.51.00_(1).txt](https://github.com/pj1234678/MagickaFix/files/13746905/errorReport_2023.12.21-05.51.00_.1.txt)

**Comment by MADCATXXX** [comment]
2 of the issues are related to out of memory exceptions, maybe better to add them to out of memory issue. But stack traces for out of memory errors are not that usefull as this can be thrown in any part of the game due to running out of heap memory (which is limited to 1.3 Gb no matter how much actual RAM you have).

**Comment by pj1234678** [comment]
What resolution are you running?

Higher resolutions require more memory.

**Comment by MishkaRose** [comment]
> What resolution are you running? Higher resolutions require more memory.

1920x1080

**Comment by MishkaRose** [comment]
these only happen when changing map / location

**Comment by pj1234678** [comment]
Thank you for the report.
I finally found a solution, Since the binary runs in 32 bit mode it can't use more than ~1.3GB of ram.
In version 1.5 I address this by adding the LARGEADDRESSAWARE flag to the binary header.

That will solve 2 out of the 3 issues you are having.

Thanks again MADCATXXX

**Comment by pj1234678** [comment]
The new version dropped Addressing a lot of these concerns
Please update and if you have the same issue open a new one.
